version: '3.3'

services:
  # PostgreSQL service
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: msiliotplatform
      POSTGRES_DB: msil-iot-digiprod-db 
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    networks:
      - my-network

  # PostgreSQL service for platform
  platform-postgres:
    image: postgres:15
    container_name: platform-postgres-db
    restart: always
    ports:
      - "5433:5432"  # Expose this database on a different port
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: msiliotplatform
      POSTGRES_DB: platform-db
    volumes:
      - platform-postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

  user-auth:
    build:
      context: ./user-auth  # Path to the service directory
      dockerfile: Dockerfile
    container_name: user-auth-prodigi1
    ports:
      - "8001:8001"
    restart: always
    networks:
      - my-network
    environment:
      - ENV=local  # Set the environment variable here
  
  backend-on-prem:
    build:
      context: ./backend-on-prem  # Path to the service directory
      dockerfile: Dockerfile
    container_name: backend-on-prem
    ports:
      - "8002:8002"
    restart: always
    networks:
      - my-network
    environment:
      - ENV=local  # Set the environment variable here

  prodigi1-batch-service:
    build:
      context: ./prodigi1-batch-service  # Path to the service directory
      dockerfile: Dockerfile
    container_name: prodigi1-batch-service
    ports:
      - "8003:8003"
    restart: always
    networks:
      - my-network
    volumes:
      - ./modules:/app/modules
    environment:
      - ENV=local  # Set the environment variable here

# Define a custom network
networks:
  my-network:
    driver: bridge

# Define a volume for PostgreSQL data persistence
volumes:
  postgres-data:
  platform-postgres-data: