class Resources(object):
    TRIGGER = "TRIGGER"
    ROLE = "ROLE"
    DEVICE = "DEVICE"
    DEVICE_CONNECT = "DEVICE_CONNECT"
    PROVISIONING = "PROVISIONING"
    SENSORS = "SENSORS"
    COMPONENTS = "COMPONENTS"
    LOGS="LOGS"
    VENUES = "VENUES"
    BUILDING_MAP = "BUILDING_MAP"
    NODERED = "NODERED"
    RULE = "RULE"
    RULE_TYPE = "RULE_TYPE"
    RULE_RUNTIME = "RULE_RUNTIME"
    PERMISSIONS = "PERMISSIONS"
    ZONE = "ZONE"
    WELDING_APIS= "WELDING_APIS"
    UPDATE_SIGNATURE = "UPDATE_SIGNATURE"
    DOWNLOAD_REPORT = "DOWNLOAD_REPORT"
    ADMIN = "ADMIN"
    PQC_SHOP = "PQC_SHOP"
    PQC_DOWNLOAD = "PQC_DOWNLOAD"
    PQC_ADMIN = "PQC_ADMIN"
    PSM_SHOP = "PSM_SHOP"
    PSM_DOWNLOAD = "PSM_DOWNLOAD"
    PSM_ADMIN = "PSM_ADMIN"


class ActionTypes(object):
    READ = "READ"
    WRITE = "WRITE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    PROVISION = "PROVISION"
    CONNECT = "CONNECT"
    ACTUATE = "ACTUATE"
    LIST = "LIST"
    UPDATE_SIGNATURE = "UPDATE_SIGNATURE"
    DOWNLOAD = "DOWNLOAD"
    ADMIN = "ADMIN"
    SHOP_ACTION = "SHOP_ACTION"
    


class Actions(object):
    GET = "GET"
    GETALL = "GETALL"
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    PROVISION = "PROVISION"
    CONNECT= "CONNECT"
    ACTUATE ="ACTUATE"
    DOWNLOAD = "DOWNLOAD"
    ADMIN = "ADMIN"
    ANY = "ANY"
   
class ProvisionLevels():
    ALL="*"
    SINGLE="SINGLE"
    BULK="BULK"

# class Scopes:
#     AREA = "AREA"
#     ZONE = "ZONE"
    
class ActuationLevels:
    ALL = "ALL"
    AREA = "AREA"
    ZONE = "ZONE"
    HYBRID = "HYBRID"
    
class LogLevels():
    ALL=0
    DEBUG=1
    INFO=2
    WARN=3
    ERROR=4

class ConnectionLevels():
    ALL="*"
    COMMAND = "COMMAND"
    CONSOLE = "CONSOLE"
    NODERED = "NODERED"

class ReadLevels():
    ALL = 0
    TENANT = 1
    USER = 2
    DISALLOWED = 3

class Scopes():
    PERMITTED = "PERMITTED"
    LEVEL = "LEVEL"
    ZONE="ZONE"
    AREA="AREA"
    ALLOWED_SHOP_IDS = "ALLOWED_SHOP_IDS"
    PROVISIONING_TYPE = "PROVISIONING_TYPE"
    CONNECTION_TYPE = "CONNECTION_TYPE"
    DETAILS = "DETAILS"
    SENSORS = "SENSORS"
    CONNECTION_HISTORY = "CONNECTION_HISTORY"

   
