FunctionName: msil-iot-get-user
EnviormentVar:
  developpressshop:
    CONNECTION_STRING_DEVELOPMENT: postgresql://postgres:msiliotplatform@msil-iot-platform-db-development.cqugg5zx1no1.ap-south-1.rds.amazonaws.com/msil-iot-platform-db
    USER_POOL_ID : ap-south-1_ZXmeb2O4l
  QApressshop:  
    CONNECTION_STRING_QA: postgresql://postgres:msiliotplatform@msil-iot-platform-uat-db.csyghq6akg4g.ap-south-1.rds.amazonaws.com/msil-iot-platform-db
    USER_POOL_ID : ap-south-1_01NMD0Giv
  productionpressshop: 
    CONNECTION_STRING: postgresql://postgres:msiliotplatform@msil-iot-platform-db.cpla9liyn1nn.ap-south-1.rds.amazonaws.com/msil-iot-platform-db
    USER_POOL_ID: ap-south-1_ZURBJNjO3
Configuration:
  Timeout: 30
  MemorySize: 128
Layer:
  - IAM
AWSPolicy:
    - service-role/AWSLambdaBasicExecutionRole
    - AmazonRDSFullAccess
    - AmazonCognitoPowerUser
    - AmazonEC2FullAccess
