apiVersion: v1
kind: Service
metadata:
  name: backend-on-prem-service
  namespace: iot-pd
spec:
  selector:
    app: backend-on-prem
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
      nodePort: 30002
  type: NodePort