apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-on-prem-deployment
  namespace: iot-pd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-on-prem
  template:
    metadata:
      labels:
        app: backend-on-prem
    spec:
      containers:
      - name: backend-on-prem
        image: localhost:32000/backend-on-prem-container:latest
        ports:
        - containerPort: 8002
        env:
        - name: ENV
          value: "dev"