apiVersion: v1
kind: Service
metadata:
  name: prodigi1-batch-service
  namespace: iot-pd
spec:
  selector:
    app: prodigi1-batch
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8003
      nodePort: 30009
  type: NodePort