UNKNOWN = "UNKNOWN"
SYSTEM = "SYSTEM"

SUCCESS = "SUCCESS"
ERROR = "ERROR"

NO_CONTENT = "NO_CONTENT"
PENDING = "PENDING"
CONFLICT = "CONFLICT"
PRE_CONDITION_REQUIRED = "PRE_CONDITION_REQUIRED"
UNPROCESSABLE_CONTENT = "UNPROCESSABLE_CONTENT"
PARAMETER_MISSING = "PARAMETER_MISSING"

SERVER_ERROR = "SERVER_ERROR"

STATUS_CODES = {
    SUCCESS: "PC200",
    NO_CONTENT: "PC204",
    PENDING: "PC300",
    PARAMETER_MISSING: "PC406",
    CONFLICT: "PC409",
    PRE_CONDITION_REQUIRED: "PC428",
    UNPROCESSABLE_CONTENT: "PC422",
    SERVER_ERROR: "PC500",
}

# Master File Status:
UPLOAD_IN_PROGRESS = "Upload In Progress"
UPLOAD_FAILED = "Upload Failed"
REVIEW_PENDING = "Review Pending"
REJECTED = "Rejected"
APPROVED = "Approved"

# CheckSheet status:
PUBLISHED = "PUBLISHED"
UNPUBLISHED = "UNPUBLISHED"
IN_PROGRESS = "IN-PROGRESS"
FAILED = "FAILED"
DISCARDED = "DISCARDED"
DEPRECATED = "DEPRECATED"


CONNECTED = "connected"
DISCONNECTED = "disconnected"