apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-dev
  namespace: prodigi-dev
data:
  nginx.conf: |
    worker_processes  auto;
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                         '$status $body_bytes_sent "$http_referer" '
                         '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;
        error_log   /var/log/nginx/error.log debug;

        include /etc/nginx/conf.d/*.conf;
    }
  default.conf: |
    server {
        listen 80;

        error_log /var/log/nginx/server_error.log debug;

        location /pressShop/sync/ {
            proxy_pass https://1huhnytnf5.execute-api.ap-south-1.amazonaws.com;
            proxy_set_header Host 1huhnytnf5.execute-api.ap-south-1.amazonaws.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            proxy_intercept_errors on;
            error_log /var/log/nginx/procheck2_sync_error.log debug;
        }

        location /platform/sync/ {
            proxy_pass https://m5d7n2vx05.execute-api.ap-south-1.amazonaws.com;
            proxy_set_header Host m5d7n2vx05.execute-api.ap-south-1.amazonaws.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_intercept_errors on;
            error_log /var/log/nginx/platform_sync_error.log debug;
        }
    }