apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-dev
  namespace: prodigi-dev
  labels:
    app: nginx-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-dev
  template:
    metadata:
      labels:
        app: nginx-dev
    spec:
      nodeSelector:
           app: pd-nginx
      containers:
      - name: nginx-dev-ctr
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 15
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        volumeMounts:
        - name: logs
          mountPath: /var/log/nginx
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config-dev
      - name: logs
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-dev
  namespace: prodigi-dev
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  selector:
    app: nginx-dev