apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-dev
  namespace: prodigi-dev
data:
 nginx.conf: |
    events { 
        worker_connections 1024;
    }
    http {
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        server {
            listen 80;

            location /pressShop/sync/ {
                proxy_pass https://xunkwvqvv7.execute-api.ap-south-1.amazonaws.com;
                proxy_set_header Host xunkwvqvv7.execute-api.ap-south-1.amazonaws.com;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            location /platform/sync/ {
                proxy_pass https://m5d7n2vx05.execute-api.ap-south-1.amazonaws.com;
                proxy_set_header Host m5d7n2vx05.execute-api.ap-south-1.amazonaws.com;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
    }