TIMEZONE = "Asia/Kolkata"

# Status
UNKNOWN = "UNKNOWN"
SYSTEM = "SYSTEM"
SUCCESS = "SUCCESS"
INPROGRESS = "INPROGRESS"
FAILED = "FAILED"

YES = "YES"
NO = "NO"

# Response Messages
NO_CONTENT = "NO_CONTENT"
PENDING = "PENDING"
CONFLICT = "CONFLICT"
PRE_CONDITION_REQUIRED = "PRE_CONDITION_REQUIRED"
UNPROCESSABLE_CONTENT = "UNPROCESSABLE_CONTENT"
PARAMETER_MISSING = "PARAMETER_MISSING"
RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
UNAUTHORIZED = "UNAUTHORIZED"
SERVER_ERROR = "SERVER_ERROR"

STATUS_CODES = {
    SUCCESS: "PC200",
    NO_CONTENT: "PC204",
    PENDING: "PC300",
    UNAUTHORIZED: "PC400",
    PARAMETER_MISSING: "PC406",
    CONFLICT: "PC409",
    PRE_CONDITION_REQUIRED: "PC428",
    UNPROCESSABLE_CONTENT: "PC422",
    SERVER_ERROR: "PC500",
    RESOURCE_NOT_FOUND: "PC404",
}

# Master File Status:
UPLOAD_IN_PROGRESS = "Upload In Progress"
UPLOAD_FAILED = "Upload Failed"
UPLOAD_SUCCESS = "Success"

SHIFTWISE = "Shiftwise"

PAGE_NUMBER = 1
PAGE_SIZE = 500